name: CI


on:
  pull_request:
    branches: [ "master", "main" ]

  push:
    branches: [ "master", "main" ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run wemake-python-styleguide checks
        uses: wemake-services/wemake-python-styleguide
